# Generated by Django 3.2 on 2023-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231103_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст отзыва'),
        ),
    ]
