# Generated by Django 3.2 on 2023-11-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231103_0335'),
        ('lesson', '0003_auto_20231103_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.comment', verbose_name='Ответ на отзыв'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publication',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='', verbose_name='Видео'),
        ),
    ]
