# Generated by Django 3.2 on 2023-11-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20231104_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Рейтинг'),
        ),
    ]
