# Generated by Django 3.2 on 2023-11-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20231103_0335'),
        ('user', '0002_auto_20231103_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_lessons', to='lesson.Lesson', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_lessons', to='lesson.Lesson', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, to='user.User', verbose_name='Подписки'),
        ),
    ]
