# Generated by Django 3.2 on 2023-11-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20231104_0815'),
        ('user', '0003_auto_20231103_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_lessons', to='lesson.Lesson', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_lessons', to='lesson.Lesson', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='Подписки'),
        ),
    ]
